pipeline:
  margarita:
    group: margarita
    image: 3.5.3-jdk-8
    commands:
      - cd margarita
      - mvn clean
      - mvn fabric8:build
  martini:
    group: martini
    image: 3.5.3-jdk-8
    commands:
      - cd martini
      - mvn clean
      - mvn fabric8:build
