pipeline:
  margarita:
    group: margarita
    image: maven:3.5.3-jdk-8
    commands:
      - cd margarita
      - ./mvnw package fabric8:resource fabric8:build
  martini:
    group: martini
    image: maven:3.5.3-jdk-8
    commands:
      - cd martini
      - ./mvnw package fabric8:resource fabric8:build
