apiVersion: v1
kind: Service
metadata:
  name: martini-cassandra-master
  labels:
    app: cassandra
    role: master
    tier: backend
spec:
  ports:
  - port: 9042
    targetPort: 9042
  selector:
    app: cassandra

