apiVersion: v1
kind: Service
metadata:
  name: martini-mongo-master
  labels:
    app: mongo
    role: master
    tier: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo

