apiVersion:  extensions/v1beta1
kind: Deployment
metadata:
  name: margarita-mongo-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
